name = "ryan-killeen-com"

workers_dev = true
main = "./build/index.js"
# https://developers.cloudflare.com/workers/platform/compatibility-dates
compatibility_date = "2022-04-05"

[site]
  bucket = "./public"

[build]
  command = "npm run build"

[vars]

# Necessary secrets
# - SANITY_PREVIEW_SECRET
# - SANITY_API_TOKEN
# https://developers.cloudflare.com/workers/platform/environment-variables/#adding-secrets-via-wrangler